"""add is_ai column to Comment table

Revision ID: d7b2921b57e7
Revises: 20679306f616
Create Date: 2024-07-04 23:17:25.674200

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd7b2921b57e7'
down_revision: Union[str, None] = '20679306f616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_ai', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_ai')
    # ### end Alembic commands ###
