version: "3.8"
services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python -m app.main"
    restart: always
    volumes:
      - .:/forum_app
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery:
    build: .
    command: celery -A app.services.celery_task worker --loglevel=DEBUG
    depends_on:
      - web
      - redis
    volumes:
      - .:/forum_app

volumes:
  pg_data:
    driver: local
  redis-data:
    driver: local
