version: "3.8"
services:
  web:
    container_name: web
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: bash -c "python -m app.main.web"
    restart: always
    volumes:
      - .:/forum_app
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "${REDIS_LOCAL_PORT}:${REDIS_PORT}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - redis-data:/data

volumes:
  pg_data:
    driver: local
  redis-data:
    driver: local
